### PR TITLE
Fix for pedronauck#17

### PR DESCRIPTION
**Pull request by atwoodjw**

### CODE REVIEW

**Comment by jgable** [comment]
Is there a reason this is not getting merged?  It fixes a couple good issues that prevent the library from being used.

**Comment by pedronauck** [comment]
Sorry guy to the delayed responses, I'm very busy in the last weeks and couldn't make support in this project because that.

First of all, thank you by the pull request. I think that we can merge everything that fix a lot of things, but... Why remove vimeo and leave only youtube @atwoodjw?

**Comment by jgable** [comment]
I would also vote against the player params changes in 510539e in favor of being able to pass those in as properties or something.  It seems @atwoodjw has abandoned his react-video repo (and these commits).  I'd vote to close this and move the first three commits to another PR.

**Comment by pedronauck** [comment]
Of course, that is the best option ;) I'll merge the new commit and update the component version...

**Pull request closed without merging**
